version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: credit-db
    ports:
      - "3307:3306"  # 左邊是電腦通道，右邊是 Docker 通道
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: graduation_system
      TZ: Asia/Taipei  # 幫資料庫設定台灣時區
    volumes:
      # 把 sql 檔，掛載進去自動執行
      - ./database/Graduation_0531_new_ver2.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 確保中文不會變亂碼