"""init_tables

Revision ID: f0a6108c0ab8
Revises: 
Create Date: 2026-06-04 20:54:21.319461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a6108c0ab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SUBJECT',
    sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('UNITS',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=20), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['UNITS.unit_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('COURSES',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['SUBJECT.subject_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['UNITS.unit_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'semester')
    )
    op.create_table('RULE',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.String(length=40), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_year', sa.Integer(), nullable=False),
    sa.Column('required_credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['UNITS.unit_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('STUDENTS',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['UNITS.unit_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('CONDITION',
    sa.Column('condition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_name', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('required_credits', sa.Integer(), nullable=False),
    sa.Column('max_admitted_credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['RULE.rule_id'], ),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('STD_COURSE_HISTORY',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id', 'semester'], ['COURSES.course_id', 'COURSES.semester'], ),
    sa.ForeignKeyConstraint(['student_id'], ['STUDENTS.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id', 'semester')
    )
    op.create_table('CONDITION_COURSE',
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['CONDITION.condition_id'], ),
    sa.ForeignKeyConstraint(['course_id', 'semester'], ['COURSES.course_id', 'COURSES.semester'], ),
    sa.PrimaryKeyConstraint('condition_id', 'course_id', 'semester')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CONDITION_COURSE')
    op.drop_table('STD_COURSE_HISTORY')
    op.drop_table('CONDITION')
    op.drop_table('STUDENTS')
    op.drop_table('RULE')
    op.drop_table('COURSES')
    op.drop_table('UNITS')
    op.drop_table('SUBJECT')
    # ### end Alembic commands ###
